name: Fork News (this is the one that actually works)
on:
  schedule:
    - cron: '00 00 * * *' # sync the repo everyday at 00:00 UTC!
  workflow_dispatch: # on button click

jobs:
  fork-news:
    runs-on: ubuntu-latest
    name: Sync with parent repository
    steps:
      - id: fork-news-sync
        uses: vitornovictor/fork-news@v1.0.0
        with:
          from-branch: main
          to-branch: main
          access-token: ${{ secrets.token }}
