name: Sync Fork

on:
  schedule:
    - cron: '20 14 * * *'
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.4
        with:
          owner: SwannedLakee
          base: master # this should match  actual name of the branch (check it with the original repo)
          head: master # this should match  actual name of the branch (check it with the original repo)
